insert into user (username, password, name, e_mail, role) values ('admin', '9d881c5692855840d531a51bfa58b1caf8fd34a67e3725c835473873b3fa3080a2e652e3588cb26ea0e6005cf2bcc7388ea433c8c2111d335c797d9d425a47ec', 'admin', 'admin@szallaskereso', 'ADMIN');
insert into user (username, password, name, e_mail, role) values ('member', 'cbf1653d6a367ae5541d7e017af1ab81e7e96c2676a2ee452bf3c15f954c9fa54022120e7d9a27c47ea5c1eca63383e29cf3350e0458eca7b720d17263c0228f','David', 'david@example', 'MEMBER');
insert into user (username, password, name, e_mail, role) values ('pelda', '2ed06239f3ac8d009c38d3721f416fc8e1951479a7d47837c6b3288e1ca1a36746d9dfea03eb4dda401a300a21bd3457142a5e5d5e9b3e7248a36fe97c151dca','Példa', 'pelda@pelda', 'MEMBER');

insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Hévíz', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Siófok', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Siófok', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Hévíz', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Hévíz', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Hévíz', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Siófok', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "wifi,medence,parkoló,légkondi", 'enddate', 2000, 1000, true, true, 1);

insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 2, 1);
insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 2, 2);
insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 2, 3);
insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 3, 4);
insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 3, 5);