
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,medence,saját parkoló,légkondi", '2022-10-01', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Hévíz', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,medence,saját parkoló,légkondi", '2022-10-01', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Siófok', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,medence,gyerekprogramok,légkondi", '2022-10-01', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Siófok', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,wellness,saját parkoló,gyerekprogramok", '2022-10-01', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,medence,saját parkoló,légkondi", '2022-10-01', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Hévíz', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,vízparti,saját parkoló,vízparti", '2022-10-01', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Hévíz', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,medence,saját vízparti,légkondi", '2022-10-01', 2000, 1000, true, false, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,medence,saját parkoló,légkondi", '2022-10-01', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,wellness,saját parkoló,légkondi", '2022-10-01', 2000, 1000, true, false, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Hévíz', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,wellness,saját vízparti,légkondi", '2022-10-01', 2000, 1000, true, false, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Siófok', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,gyerekprogramok,saját parkoló,légkondi", '2022-10-01', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,wellness,saját parkoló,vízparti", '2022-10-01', 2000, 1000, true, false, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,medence,saját parkoló,légkondi", '2022-10-01', 2000, 1000, true, true, 1);
insert into accommodation (name, place, phone_number, description, information, services, res_end_date, adult_price, child_price, active, confirmed, user_id) values ('Valami Hotel', 'Budapest', 123456789, 'Hosszabb leirás a szállodáról és környezetéről', 'Informaciok', "ingyen wifi,medence,saját parkoló,légkondi", '2022-10-01', 2000, 1000, true, true, 1);

insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 2, 1);
insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 2, 2);
insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 2, 3);
insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 3, 4);
insert into reservation (start_date, end_date, adults, children, user_id, accommodation_id) values ('2022-05-08', '2022-05-15', 2, 1, 3, 5);